create table EXCHANGE (
    ID INT AUTO_INCREMENT PRIMARY KEY
    , FROM_CURRENCY VARCHAR2(50)
    , TO_CURRENCY VARCHAR2(50)
    , EXCHANGE_RATE DECIMAL
    , EXCHANGE_DATE DATE
    , VERSION INT
    , STATUS INT
);